package view;

import static application.MainApp.ListaMesa;
import static application.MainApp.ListaProduto;
import static application.MainApp.comandaAtiva;
import static application.MainApp.comandaController;
import static application.MainApp.mesaAtiva;
import static application.MainApp.mesaController;
import static application.MainApp.pedidoController;
import static application.MainApp.produtoController;
import controler.ComandaController;
import controler.MesaController;
import controler.PedidoController;
import controler.StatusMesa;
import controler.StatuspPagamento;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.FlowLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import model.Comanda;
import model.Mesa;
import model.Pedido;
import model.Produto;

/**
 *
 * @author Aluno
 */

public class frmComanda extends javax.swing.JFrame {

    /**
     * Creates new form frmComanda
     */        
    
    public frmComanda() {
               initComponents();        
        this.jLabel8.setText(Integer.toString(comandaAtiva.getNumeroMesa()));        
//        this.jTextField1.setText(comandaAtiva.getCliente().getNomeCliente());                                
        carregaMenu();
        
        // Define a cor de fundo do JFrame para preto
        getContentPane().setBackground(Color.PINK);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);        
        // Se estiver usando um JPanel ou outros componentes, defina a cor de fundo também
        JPanel panel = new JPanel();
        panel.setBackground(Color.PINK); // Define a cor de fundo do JPanel para preto
        panel.setLayout(new FlowLayout()); // L              

        int intComanda = comandaController.buscarComandaAbertaPorMesa(comandaAtiva.getNumeroMesa()).getIdComanda();                        
        this.jLabel9.setText(Integer.toString(intComanda));        
        
        
    }

    private void carregaMenu() {
        // Obtém os componentes do JPanel
        Component[] components = jPanel1.getComponents();

        // Torna todos os JButton invisíveis inicialmente
        for (Component component : components) {
            if (component instanceof JButton) {
                component.setVisible(false);
            }
        }

        // Atualiza os JButtons visíveis conforme os produtos
        for (Produto produto : ListaProduto) {
            int idProduto = produto.getIdProduto();
            if (idProduto >= 1 && idProduto <= components.length) {
                Component comp = components[idProduto - 1];
                if (comp instanceof JButton) {
                    JButton button = (JButton) comp;
                    button.setText(produto.getDescricaoProduto());
                    button.setVisible(true);
                }
            }
        }       
        
    }

    private void adicionarProduto(String produtoDesc){
        
        // Atualiza os JButtons visíveis conforme os produtos
        for (Produto produto : ListaProduto) {
            if (produto.getDescricaoProduto() == produtoDesc){
                
                
            }
        }
        

    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jButton102 = new javax.swing.JButton();
        jButton103 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jButton109 = new javax.swing.JButton();
        jButton110 = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();
        jButton112 = new javax.swing.JButton();
        jButton113 = new javax.swing.JButton();
        jButton114 = new javax.swing.JButton();
        jButton115 = new javax.swing.JButton();
        jButton116 = new javax.swing.JButton();
        jButton117 = new javax.swing.JButton();
        jButton118 = new javax.swing.JButton();
        jButton119 = new javax.swing.JButton();
        jButton120 = new javax.swing.JButton();
        jButton121 = new javax.swing.JButton();
        jButton122 = new javax.swing.JButton();
        jButton123 = new javax.swing.JButton();
        jButton124 = new javax.swing.JButton();
        jButton125 = new javax.swing.JButton();
        jButton126 = new javax.swing.JButton();
        jButton127 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setName("txtCardapioRapido"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(30, 5, 3, 3));

        jButton5.setText("#ProdutoMenu");
        jButton5.setToolTipText("");
        jButton5.setBorderPainted(false);
        jButton5.setSelected(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton6.setText("#ProdutoMenu");
        jButton6.setToolTipText("");
        jButton6.setBorderPainted(false);
        jButton6.setSelected(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButton7.setText("#ProdutoMenu");
        jButton7.setToolTipText("");
        jButton7.setBorderPainted(false);
        jButton7.setSelected(true);
        jPanel1.add(jButton7);

        jButton8.setText("#ProdutoMenu");
        jButton8.setToolTipText("");
        jButton8.setBorderPainted(false);
        jButton8.setSelected(true);
        jPanel1.add(jButton8);

        jButton9.setText("#ProdutoMenu");
        jButton9.setToolTipText("");
        jButton9.setBorderPainted(false);
        jButton9.setSelected(true);
        jPanel1.add(jButton9);

        jButton10.setText("#ProdutoMenu");
        jButton10.setToolTipText("");
        jButton10.setBorderPainted(false);
        jButton10.setSelected(true);
        jPanel1.add(jButton10);

        jButton11.setText("#ProdutoMenu");
        jButton11.setToolTipText("");
        jButton11.setBorderPainted(false);
        jButton11.setSelected(true);
        jPanel1.add(jButton11);

        jButton12.setText("#ProdutoMenu");
        jButton12.setToolTipText("");
        jButton12.setBorderPainted(false);
        jButton12.setSelected(true);
        jPanel1.add(jButton12);

        jButton13.setText("#ProdutoMenu");
        jButton13.setToolTipText("");
        jButton13.setBorderPainted(false);
        jButton13.setSelected(true);
        jPanel1.add(jButton13);

        jButton14.setText("#ProdutoMenu");
        jButton14.setToolTipText("");
        jButton14.setBorderPainted(false);
        jButton14.setSelected(true);
        jPanel1.add(jButton14);

        jButton15.setText("#ProdutoMenu");
        jButton15.setToolTipText("");
        jButton15.setBorderPainted(false);
        jButton15.setSelected(true);
        jPanel1.add(jButton15);

        jButton16.setText("#ProdutoMenu");
        jButton16.setToolTipText("");
        jButton16.setBorderPainted(false);
        jButton16.setSelected(true);
        jPanel1.add(jButton16);

        jButton17.setText("#ProdutoMenu");
        jButton17.setToolTipText("");
        jButton17.setBorderPainted(false);
        jButton17.setSelected(true);
        jPanel1.add(jButton17);

        jButton18.setText("#ProdutoMenu");
        jButton18.setToolTipText("");
        jButton18.setBorderPainted(false);
        jButton18.setSelected(true);
        jPanel1.add(jButton18);

        jButton19.setText("#ProdutoMenu");
        jButton19.setToolTipText("");
        jButton19.setBorderPainted(false);
        jButton19.setSelected(true);
        jPanel1.add(jButton19);

        jButton23.setText("#ProdutoMenu");
        jButton23.setToolTipText("");
        jButton23.setBorderPainted(false);
        jButton23.setSelected(true);
        jPanel1.add(jButton23);

        jButton24.setText("#ProdutoMenu");
        jButton24.setToolTipText("");
        jButton24.setBorderPainted(false);
        jButton24.setSelected(true);
        jPanel1.add(jButton24);

        jButton25.setText("#ProdutoMenu");
        jButton25.setToolTipText("");
        jButton25.setBorderPainted(false);
        jButton25.setSelected(true);
        jPanel1.add(jButton25);

        jButton26.setText("#ProdutoMenu");
        jButton26.setToolTipText("");
        jButton26.setBorderPainted(false);
        jButton26.setSelected(true);
        jPanel1.add(jButton26);

        jButton27.setText("#ProdutoMenu");
        jButton27.setToolTipText("");
        jButton27.setBorderPainted(false);
        jButton27.setSelected(true);
        jPanel1.add(jButton27);

        jButton28.setText("#ProdutoMenu");
        jButton28.setToolTipText("");
        jButton28.setBorderPainted(false);
        jButton28.setSelected(true);
        jPanel1.add(jButton28);

        jButton29.setText("#ProdutoMenu");
        jButton29.setToolTipText("");
        jButton29.setBorderPainted(false);
        jButton29.setSelected(true);
        jPanel1.add(jButton29);

        jButton30.setText("#ProdutoMenu");
        jButton30.setToolTipText("");
        jButton30.setBorderPainted(false);
        jButton30.setSelected(true);
        jPanel1.add(jButton30);

        jButton31.setText("#ProdutoMenu");
        jButton31.setToolTipText("");
        jButton31.setBorderPainted(false);
        jButton31.setSelected(true);
        jPanel1.add(jButton31);

        jButton32.setText("#ProdutoMenu");
        jButton32.setToolTipText("");
        jButton32.setBorderPainted(false);
        jButton32.setSelected(true);
        jPanel1.add(jButton32);

        jButton33.setText("#ProdutoMenu");
        jButton33.setToolTipText("");
        jButton33.setBorderPainted(false);
        jButton33.setSelected(true);
        jPanel1.add(jButton33);

        jButton34.setText("#ProdutoMenu");
        jButton34.setToolTipText("");
        jButton34.setBorderPainted(false);
        jButton34.setSelected(true);
        jPanel1.add(jButton34);

        jButton35.setText("#ProdutoMenu");
        jButton35.setToolTipText("");
        jButton35.setBorderPainted(false);
        jButton35.setSelected(true);
        jPanel1.add(jButton35);

        jButton36.setText("#ProdutoMenu");
        jButton36.setToolTipText("");
        jButton36.setBorderPainted(false);
        jButton36.setSelected(true);
        jPanel1.add(jButton36);

        jButton37.setText("#ProdutoMenu");
        jButton37.setToolTipText("");
        jButton37.setBorderPainted(false);
        jButton37.setSelected(true);
        jPanel1.add(jButton37);

        jButton38.setText("#ProdutoMenu");
        jButton38.setToolTipText("");
        jButton38.setBorderPainted(false);
        jButton38.setSelected(true);
        jPanel1.add(jButton38);

        jButton39.setText("#ProdutoMenu");
        jButton39.setToolTipText("");
        jButton39.setBorderPainted(false);
        jButton39.setSelected(true);
        jPanel1.add(jButton39);

        jButton40.setText("#ProdutoMenu");
        jButton40.setToolTipText("");
        jButton40.setBorderPainted(false);
        jButton40.setSelected(true);
        jPanel1.add(jButton40);

        jButton41.setText("#ProdutoMenu");
        jButton41.setToolTipText("");
        jButton41.setBorderPainted(false);
        jButton41.setSelected(true);
        jPanel1.add(jButton41);

        jButton42.setText("#ProdutoMenu");
        jButton42.setToolTipText("");
        jButton42.setBorderPainted(false);
        jButton42.setSelected(true);
        jPanel1.add(jButton42);

        jButton43.setText("#ProdutoMenu");
        jButton43.setToolTipText("");
        jButton43.setBorderPainted(false);
        jButton43.setSelected(true);
        jPanel1.add(jButton43);

        jButton44.setText("#ProdutoMenu");
        jButton44.setToolTipText("");
        jButton44.setBorderPainted(false);
        jButton44.setSelected(true);
        jPanel1.add(jButton44);

        jButton45.setText("#ProdutoMenu");
        jButton45.setToolTipText("");
        jButton45.setBorderPainted(false);
        jButton45.setSelected(true);
        jPanel1.add(jButton45);

        jButton46.setText("#ProdutoMenu");
        jButton46.setToolTipText("");
        jButton46.setBorderPainted(false);
        jButton46.setSelected(true);
        jPanel1.add(jButton46);

        jButton47.setText("#ProdutoMenu");
        jButton47.setToolTipText("");
        jButton47.setBorderPainted(false);
        jButton47.setSelected(true);
        jPanel1.add(jButton47);

        jButton48.setText("#ProdutoMenu");
        jButton48.setToolTipText("");
        jButton48.setBorderPainted(false);
        jButton48.setSelected(true);
        jPanel1.add(jButton48);

        jButton49.setText("#ProdutoMenu");
        jButton49.setToolTipText("");
        jButton49.setBorderPainted(false);
        jButton49.setSelected(true);
        jPanel1.add(jButton49);

        jButton50.setText("#ProdutoMenu");
        jButton50.setToolTipText("");
        jButton50.setBorderPainted(false);
        jButton50.setSelected(true);
        jPanel1.add(jButton50);

        jButton51.setText("#ProdutoMenu");
        jButton51.setToolTipText("");
        jButton51.setBorderPainted(false);
        jButton51.setSelected(true);
        jPanel1.add(jButton51);

        jButton52.setText("#ProdutoMenu");
        jButton52.setToolTipText("");
        jButton52.setBorderPainted(false);
        jButton52.setSelected(true);
        jPanel1.add(jButton52);

        jButton53.setText("#ProdutoMenu");
        jButton53.setToolTipText("");
        jButton53.setBorderPainted(false);
        jButton53.setSelected(true);
        jPanel1.add(jButton53);

        jButton54.setText("#ProdutoMenu");
        jButton54.setToolTipText("");
        jButton54.setBorderPainted(false);
        jButton54.setSelected(true);
        jPanel1.add(jButton54);

        jButton55.setText("#ProdutoMenu");
        jButton55.setToolTipText("");
        jButton55.setBorderPainted(false);
        jButton55.setSelected(true);
        jPanel1.add(jButton55);

        jButton56.setText("#ProdutoMenu");
        jButton56.setToolTipText("");
        jButton56.setBorderPainted(false);
        jButton56.setSelected(true);
        jPanel1.add(jButton56);

        jButton57.setText("#ProdutoMenu");
        jButton57.setToolTipText("");
        jButton57.setBorderPainted(false);
        jButton57.setSelected(true);
        jPanel1.add(jButton57);

        jButton58.setText("#ProdutoMenu");
        jButton58.setToolTipText("");
        jButton58.setBorderPainted(false);
        jButton58.setSelected(true);
        jPanel1.add(jButton58);

        jButton59.setText("#ProdutoMenu");
        jButton59.setToolTipText("");
        jButton59.setBorderPainted(false);
        jButton59.setSelected(true);
        jPanel1.add(jButton59);

        jButton60.setText("#ProdutoMenu");
        jButton60.setToolTipText("");
        jButton60.setBorderPainted(false);
        jButton60.setSelected(true);
        jPanel1.add(jButton60);

        jButton61.setText("#ProdutoMenu");
        jButton61.setToolTipText("");
        jButton61.setBorderPainted(false);
        jButton61.setSelected(true);
        jPanel1.add(jButton61);

        jButton62.setText("#ProdutoMenu");
        jButton62.setToolTipText("");
        jButton62.setBorderPainted(false);
        jButton62.setSelected(true);
        jPanel1.add(jButton62);

        jButton63.setText("#ProdutoMenu");
        jButton63.setToolTipText("");
        jButton63.setBorderPainted(false);
        jButton63.setSelected(true);
        jPanel1.add(jButton63);

        jButton64.setText("#ProdutoMenu");
        jButton64.setToolTipText("");
        jButton64.setBorderPainted(false);
        jButton64.setSelected(true);
        jPanel1.add(jButton64);

        jButton65.setText("#ProdutoMenu");
        jButton65.setToolTipText("");
        jButton65.setBorderPainted(false);
        jButton65.setSelected(true);
        jPanel1.add(jButton65);

        jButton66.setText("#ProdutoMenu");
        jButton66.setToolTipText("");
        jButton66.setBorderPainted(false);
        jButton66.setSelected(true);
        jPanel1.add(jButton66);

        jButton67.setText("#ProdutoMenu");
        jButton67.setToolTipText("");
        jButton67.setBorderPainted(false);
        jButton67.setSelected(true);
        jPanel1.add(jButton67);

        jButton68.setText("#ProdutoMenu");
        jButton68.setToolTipText("");
        jButton68.setBorderPainted(false);
        jButton68.setSelected(true);
        jPanel1.add(jButton68);

        jButton69.setText("#ProdutoMenu");
        jButton69.setToolTipText("");
        jButton69.setBorderPainted(false);
        jButton69.setSelected(true);
        jPanel1.add(jButton69);

        jButton70.setText("#ProdutoMenu");
        jButton70.setToolTipText("");
        jButton70.setBorderPainted(false);
        jButton70.setSelected(true);
        jPanel1.add(jButton70);

        jButton71.setText("#ProdutoMenu");
        jButton71.setToolTipText("");
        jButton71.setBorderPainted(false);
        jButton71.setSelected(true);
        jPanel1.add(jButton71);

        jButton72.setText("#ProdutoMenu");
        jButton72.setToolTipText("");
        jButton72.setBorderPainted(false);
        jButton72.setSelected(true);
        jPanel1.add(jButton72);

        jButton73.setText("#ProdutoMenu");
        jButton73.setToolTipText("");
        jButton73.setBorderPainted(false);
        jButton73.setSelected(true);
        jPanel1.add(jButton73);

        jButton74.setText("#ProdutoMenu");
        jButton74.setToolTipText("");
        jButton74.setBorderPainted(false);
        jButton74.setSelected(true);
        jPanel1.add(jButton74);

        jButton75.setText("#ProdutoMenu");
        jButton75.setToolTipText("");
        jButton75.setBorderPainted(false);
        jButton75.setSelected(true);
        jPanel1.add(jButton75);

        jButton76.setText("#ProdutoMenu");
        jButton76.setToolTipText("");
        jButton76.setBorderPainted(false);
        jButton76.setSelected(true);
        jPanel1.add(jButton76);

        jButton77.setText("#ProdutoMenu");
        jButton77.setToolTipText("");
        jButton77.setBorderPainted(false);
        jButton77.setSelected(true);
        jPanel1.add(jButton77);

        jButton78.setText("#ProdutoMenu");
        jButton78.setToolTipText("");
        jButton78.setBorderPainted(false);
        jButton78.setSelected(true);
        jPanel1.add(jButton78);

        jButton79.setText("#ProdutoMenu");
        jButton79.setToolTipText("");
        jButton79.setBorderPainted(false);
        jButton79.setSelected(true);
        jPanel1.add(jButton79);

        jButton80.setText("#ProdutoMenu");
        jButton80.setToolTipText("");
        jButton80.setBorderPainted(false);
        jButton80.setSelected(true);
        jPanel1.add(jButton80);

        jButton81.setText("#ProdutoMenu");
        jButton81.setToolTipText("");
        jButton81.setBorderPainted(false);
        jButton81.setSelected(true);
        jPanel1.add(jButton81);

        jButton82.setText("#ProdutoMenu");
        jButton82.setToolTipText("");
        jButton82.setBorderPainted(false);
        jButton82.setSelected(true);
        jPanel1.add(jButton82);

        jButton83.setText("#ProdutoMenu");
        jButton83.setToolTipText("");
        jButton83.setBorderPainted(false);
        jButton83.setSelected(true);
        jPanel1.add(jButton83);

        jButton84.setText("#ProdutoMenu");
        jButton84.setToolTipText("");
        jButton84.setBorderPainted(false);
        jButton84.setSelected(true);
        jPanel1.add(jButton84);

        jButton85.setText("#ProdutoMenu");
        jButton85.setToolTipText("");
        jButton85.setBorderPainted(false);
        jButton85.setSelected(true);
        jPanel1.add(jButton85);

        jButton86.setText("#ProdutoMenu");
        jButton86.setToolTipText("");
        jButton86.setBorderPainted(false);
        jButton86.setSelected(true);
        jPanel1.add(jButton86);

        jButton87.setText("#ProdutoMenu");
        jButton87.setToolTipText("");
        jButton87.setBorderPainted(false);
        jButton87.setSelected(true);
        jPanel1.add(jButton87);

        jButton88.setText("#ProdutoMenu");
        jButton88.setToolTipText("");
        jButton88.setBorderPainted(false);
        jButton88.setSelected(true);
        jPanel1.add(jButton88);

        jButton89.setText("#ProdutoMenu");
        jButton89.setToolTipText("");
        jButton89.setBorderPainted(false);
        jButton89.setSelected(true);
        jPanel1.add(jButton89);

        jButton90.setText("#ProdutoMenu");
        jButton90.setToolTipText("");
        jButton90.setBorderPainted(false);
        jButton90.setSelected(true);
        jPanel1.add(jButton90);

        jButton91.setText("#ProdutoMenu");
        jButton91.setToolTipText("");
        jButton91.setBorderPainted(false);
        jButton91.setSelected(true);
        jPanel1.add(jButton91);

        jButton92.setText("#ProdutoMenu");
        jButton92.setToolTipText("");
        jButton92.setBorderPainted(false);
        jButton92.setSelected(true);
        jPanel1.add(jButton92);

        jButton93.setText("#ProdutoMenu");
        jButton93.setToolTipText("");
        jButton93.setBorderPainted(false);
        jButton93.setSelected(true);
        jPanel1.add(jButton93);

        jButton94.setText("#ProdutoMenu");
        jButton94.setToolTipText("");
        jButton94.setBorderPainted(false);
        jButton94.setSelected(true);
        jPanel1.add(jButton94);

        jButton95.setText("#ProdutoMenu");
        jButton95.setToolTipText("");
        jButton95.setBorderPainted(false);
        jButton95.setSelected(true);
        jPanel1.add(jButton95);

        jButton96.setText("#ProdutoMenu");
        jButton96.setToolTipText("");
        jButton96.setBorderPainted(false);
        jButton96.setSelected(true);
        jPanel1.add(jButton96);

        jButton97.setText("#ProdutoMenu");
        jButton97.setToolTipText("");
        jButton97.setBorderPainted(false);
        jButton97.setSelected(true);
        jPanel1.add(jButton97);

        jButton98.setText("#ProdutoMenu");
        jButton98.setToolTipText("");
        jButton98.setBorderPainted(false);
        jButton98.setSelected(true);
        jPanel1.add(jButton98);

        jButton99.setText("#ProdutoMenu");
        jButton99.setToolTipText("");
        jButton99.setBorderPainted(false);
        jButton99.setSelected(true);
        jPanel1.add(jButton99);

        jButton100.setText("#ProdutoMenu");
        jButton100.setToolTipText("");
        jButton100.setBorderPainted(false);
        jButton100.setSelected(true);
        jPanel1.add(jButton100);

        jButton101.setText("#ProdutoMenu");
        jButton101.setToolTipText("");
        jButton101.setBorderPainted(false);
        jButton101.setSelected(true);
        jPanel1.add(jButton101);

        jButton102.setText("#ProdutoMenu");
        jButton102.setToolTipText("");
        jButton102.setBorderPainted(false);
        jButton102.setSelected(true);
        jPanel1.add(jButton102);

        jButton103.setText("#ProdutoMenu");
        jButton103.setToolTipText("");
        jButton103.setBorderPainted(false);
        jButton103.setSelected(true);
        jPanel1.add(jButton103);

        jButton104.setText("#ProdutoMenu");
        jButton104.setToolTipText("");
        jButton104.setBorderPainted(false);
        jButton104.setSelected(true);
        jPanel1.add(jButton104);

        jButton105.setText("#ProdutoMenu");
        jButton105.setToolTipText("");
        jButton105.setBorderPainted(false);
        jButton105.setSelected(true);
        jPanel1.add(jButton105);

        jButton106.setText("#ProdutoMenu");
        jButton106.setToolTipText("");
        jButton106.setBorderPainted(false);
        jButton106.setSelected(true);
        jPanel1.add(jButton106);

        jButton107.setText("#ProdutoMenu");
        jButton107.setToolTipText("");
        jButton107.setBorderPainted(false);
        jButton107.setSelected(true);
        jPanel1.add(jButton107);

        jButton108.setText("#ProdutoMenu");
        jButton108.setToolTipText("");
        jButton108.setBorderPainted(false);
        jButton108.setSelected(true);
        jPanel1.add(jButton108);

        jButton109.setText("#ProdutoMenu");
        jButton109.setToolTipText("");
        jButton109.setBorderPainted(false);
        jButton109.setSelected(true);
        jPanel1.add(jButton109);

        jButton110.setText("#ProdutoMenu");
        jButton110.setToolTipText("");
        jButton110.setBorderPainted(false);
        jButton110.setSelected(true);
        jPanel1.add(jButton110);

        jButton111.setText("#ProdutoMenu");
        jButton111.setToolTipText("");
        jButton111.setBorderPainted(false);
        jButton111.setSelected(true);
        jPanel1.add(jButton111);

        jButton112.setText("#ProdutoMenu");
        jButton112.setToolTipText("");
        jButton112.setBorderPainted(false);
        jButton112.setSelected(true);
        jPanel1.add(jButton112);

        jButton113.setText("#ProdutoMenu");
        jButton113.setToolTipText("");
        jButton113.setBorderPainted(false);
        jButton113.setSelected(true);
        jPanel1.add(jButton113);

        jButton114.setText("#ProdutoMenu");
        jButton114.setToolTipText("");
        jButton114.setBorderPainted(false);
        jButton114.setSelected(true);
        jPanel1.add(jButton114);

        jButton115.setText("#ProdutoMenu");
        jButton115.setToolTipText("");
        jButton115.setBorderPainted(false);
        jButton115.setSelected(true);
        jPanel1.add(jButton115);

        jButton116.setText("#ProdutoMenu");
        jButton116.setToolTipText("");
        jButton116.setBorderPainted(false);
        jButton116.setSelected(true);
        jPanel1.add(jButton116);

        jButton117.setText("#ProdutoMenu");
        jButton117.setToolTipText("");
        jButton117.setBorderPainted(false);
        jButton117.setSelected(true);
        jPanel1.add(jButton117);

        jButton118.setText("#ProdutoMenu");
        jButton118.setToolTipText("");
        jButton118.setBorderPainted(false);
        jButton118.setSelected(true);
        jPanel1.add(jButton118);

        jButton119.setText("#ProdutoMenu");
        jButton119.setToolTipText("");
        jButton119.setBorderPainted(false);
        jButton119.setSelected(true);
        jPanel1.add(jButton119);

        jButton120.setText("#ProdutoMenu");
        jButton120.setToolTipText("");
        jButton120.setBorderPainted(false);
        jButton120.setSelected(true);
        jPanel1.add(jButton120);

        jButton121.setText("#ProdutoMenu");
        jButton121.setToolTipText("");
        jButton121.setBorderPainted(false);
        jButton121.setSelected(true);
        jPanel1.add(jButton121);

        jButton122.setText("#ProdutoMenu");
        jButton122.setToolTipText("");
        jButton122.setBorderPainted(false);
        jButton122.setSelected(true);
        jPanel1.add(jButton122);

        jButton123.setText("#ProdutoMenu");
        jButton123.setToolTipText("");
        jButton123.setBorderPainted(false);
        jButton123.setSelected(true);
        jPanel1.add(jButton123);

        jButton124.setText("#ProdutoMenu");
        jButton124.setToolTipText("");
        jButton124.setBorderPainted(false);
        jButton124.setSelected(true);
        jPanel1.add(jButton124);

        jButton125.setText("#ProdutoMenu");
        jButton125.setToolTipText("");
        jButton125.setBorderPainted(false);
        jButton125.setSelected(true);
        jPanel1.add(jButton125);

        jButton126.setText("#ProdutoMenu");
        jButton126.setToolTipText("");
        jButton126.setBorderPainted(false);
        jButton126.setSelected(true);
        jPanel1.add(jButton126);

        jButton127.setText("#ProdutoMenu");
        jButton127.setToolTipText("");
        jButton127.setBorderPainted(false);
        jButton127.setSelected(true);
        jPanel1.add(jButton127);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Sair da Comanda");
        jButton1.setName("Sair"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setText("Imprimir Preparo");
        jPanel3.add(jButton2);

        jButton3.setText("Finalizar Venda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        jButton4.setText("Cancelar Venda");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setText("QUANTIDADE");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(255, 153, 0));

        jLabel2.setText("PREÇO UNITÁRIO");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item", "Descrição", "Preço Unit.", "Quantidade", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton20.setText("Buscar");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setText("Buscar");

        jButton22.setText("Excluir Item");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jLabel4.setText("Código");

        jLabel5.setText("Descrição do Item");

        jLabel6.setText("Cliente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jTextField3))))
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 153, 255));
        jPanel5.setName("txtComanda"); // NOI18N

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Comanda:");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("1");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cadápio Rápido");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("1");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Mesa :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(27, 27, 27)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
        int intComanda = comandaController.buscarComandaAbertaPorMesa(comandaAtiva.getNumeroMesa()).getIdComanda();                        
        comandaController.FechaComanda(intComanda);        
        mesaAtiva.setStatusMesa(StatusMesa.LIVRE); 
        mesaController.atualizarMesa(mesaAtiva);        
        this.dispose();
        JFrame frmPagamento = new frmPagamento();
        frmPagamento.setVisible(true);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        for (Produto produto : produtoController.listarProdutos()) {
            if (produto.getDescricaoProduto()==this.jButton5.getText()){                      
                Pedido pedidoNovo = new Pedido(comandaAtiva.getIdComanda(), produto.getIdProduto(), 1, produto.getValorUnitarioProduto());
                application.Utils.DialogBoxes.MessageBox("Criou", "");
                pedidoController.criarPedido(pedidoNovo);
            }
        }                
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

         for (Produto produto : produtoController.listarProdutos()) {
            if (produto.getDescricaoProduto()==this.jButton6.getText()){                      
                Pedido pedidoNovo = new Pedido(comandaAtiva.getIdComanda(), produto.getIdProduto(), 1, produto.getValorUnitarioProduto());
                application.Utils.DialogBoxes.MessageBox("Criou", "");
                pedidoController.criarPedido(pedidoNovo);
            }
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmComanda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton115;
    private javax.swing.JButton jButton116;
    private javax.swing.JButton jButton117;
    private javax.swing.JButton jButton118;
    private javax.swing.JButton jButton119;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton120;
    private javax.swing.JButton jButton121;
    private javax.swing.JButton jButton122;
    private javax.swing.JButton jButton123;
    private javax.swing.JButton jButton124;
    private javax.swing.JButton jButton125;
    private javax.swing.JButton jButton126;
    private javax.swing.JButton jButton127;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
