package view;

import static application.MainApp.CarregaListas;
import static application.MainApp.ListaAtendetes;
import static application.MainApp.ListaClientes;
import static application.MainApp.ListaComanda;
import static application.MainApp.ListaMesa;
import static application.MainApp.ListaPagamento;
import static application.MainApp.ListaPedido;
import static application.MainApp.ListaProduto;
import application.Database_Alquimia;
import static application.Database_Alquimia.checkDatabase;
import java.awt.Cursor;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Sessoes
     */
    public Splash() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        initComponents();                
    try {

            if (checkDatabase()){                                                         
                this.dispose();
            } else {                
                Database_Alquimia.prepareEnvironment();                
                if (checkDatabase()){                                             
                    
                    this.dispose();            
                }
            }
            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro na conexão ao banco de dados!");            
                this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            }        // TODO add your handling code here:        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 124)); // NOI18N
        jLabel1.setText("Cine");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 124)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("ABC");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("2023. Versão 1.0.0.0");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(932, 467));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("2024. Versão 1.0.0.0");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 400, 214, 30);

        jProgressBar1.setForeground(new java.awt.Color(255, 0, 255));
        jProgressBar1.setValue(50);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(280, 380, 380, 22);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setAlignmentY(0.0F);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 940, 467);

        getAccessibleContext().setAccessibleParent(this);

        setSize(new java.awt.Dimension(933, 466));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        
        try {
            pausarExecucao(1000);                
            JFrame frmLogin = new frmLoginDB();            
            ListaClientes = application.MainApp.clienteController.listarClientes();
            this.jProgressBar1.setValue(20);
            ListaAtendetes = application.MainApp.atendenteController.listarAtendentes();
            this.repaint();        
            ListaComanda = application.MainApp.comandaController.listarComandas();
            this.jProgressBar1.setValue(30);
            this.repaint();                    
            ListaMesa = application.MainApp.mesaController.listarMesas();
            this.jProgressBar1.setValue(40);
            this.repaint();        
            ListaPagamento = application.MainApp.pagamentoController.listarPagamentos();
            this.jProgressBar1.setValue(50);
            this.repaint();        
            ListaPedido = application.MainApp.pedidoController.listarPedidos();
            this.jProgressBar1.setValue(60);
            this.repaint();        
            ListaProduto = application.MainApp.produtoController.listarProdutos();
            this.jProgressBar1.setValue(70);
            this.repaint();        
            application.Database_Alquimia.prepareEnvironment();
            this.dispose();
            frmLogin.setVisible(rootPaneCheckingEnabled);
        } catch (Exception e) {
        }


    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }
    

    public static void pausarExecucao(long milissegundos) {
        try {
            Thread.sleep(milissegundos);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
